name: Check Code CI
on: [pull_request]

jobs:
  build:
    name: Detekt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Run Action Detekt
        uses: alaegin/Detekt-Action@v1.21.0-RC2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          detekt_config: config/detekt-config.yml
          fail_on_error: true
          detekt_parallel: true
          detekt_all_rules: true
          reviewdog_reporter: github-pr-review
          reviewdog_level: error,info,warning

